'''
Module to store map metadata for lookup in the mapinfo module, to get the hash use average hash (ahash) from the imagehash module.

example maps entry: {'ahash': {'name': 'map name',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
                     ...}
'''

maps = {'f0f0e0e0e0f8f8fe': {'name': 'Zaandam,_Nederlands', #Ground Maps
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '7f7b33f300070001': {'name': 'Eastern_Europe',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '09b36100f4f6fefa': {'name': 'Battle_of_Berlin',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'c0607e5e1b707e3c': {'name': 'Jungle',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '000000c0f0ffffff': {'name': 'El_Alamein',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '000820e066cf9fff': {'name': 'Frozen_Pass',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'fffe1c08081f1f3f': {'name': 'Finland',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '181a73fce5e1c103': {'name': 'Battle_of_Hürtgen_Forest',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '80c48280c3dfffff': {'name': 'Ash_River',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '3b80beb8b87c88f0': {'name': 'Karelia',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '003cf9f3f0e2d22c': {'name': 'Carpathians',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '80c0f0f8d8fcf8f0': {'name': 'Fire_Arc',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'fffeed614361e160': {'name': 'Kuban',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '7d0d0c3133030301': {'name': 'Mozdok',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'c03c642113537176': {'name': 'Normandy',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'f86170b2030f3f09': {'name': 'Poland',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'e380a0c8c899ece6': {'name': 'Advance_to_the_Rhine',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '3f807efcfefcf0f1': {'name': 'Stalingrad',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'eefcfe0000fefefe': {'name': 'Tunisia',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'f7ed4d49e8d8fc3e': {'name': 'Volokalamsk',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'f2f8ece2f0f8fcfe': {'name': 'Sinai',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '2f07030080c1e3df': {'name': '38th_Parallel',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'ff5f3f0702060f1f': {'name': 'Abandoned_Factory',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'dfe0809061ffdfd0': {'name': 'Ardennes',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'e0e0c0c0c08fffff': {'name': 'Japan',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '083e1e7c7870f0c0': {'name': 'Fulda',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'fcfefdff7e380001': {'name': 'Syria',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'ef0f0f1606040800': {'name': 'Maginot_Line',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '00007e7e7e7e3800': {'name': 'Campania',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'fcfcf99900befc0c': {'name': 'American_Desert',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '013e3c7cfefe7c08': {'name': 'Vietnam',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '0e3efe78f8fc1e0c': {'name': 'Alaska',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '00307c7c3c3c3c00': {'name': 'Cargo_Port',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '003c7e7e7e7c3c00': {'name': 'Sweden',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '9f1b3efebe660090': {'name': 'Syevyersk-13',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'df81d9e0e0e981db': {'name': 'Ennedi_Plateau',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '98883e3e3e0e0e8c': {'name': 'Breslau',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '79c4dcf1e187e2e0': {'name': 'Launch_Facility',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'fbffffc6c2c2c880': {'name': 'Aral_teńizi',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'f0f8f8e0c0e0f8f8': {'name': 'Avnat_Isreal',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '0ebcfe78f87c1e0c': {'name': 'Ground_Zero',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'c0f0fcfece604080': {'name': 'Tkvarcheli_District',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'f3f7a282d3e3e3f9': {'name': 'Himalach_Pradesh',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'e4fcfcfedf1c2aef': {'name': 'Arcic_Pier',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '0f47c38008b88fe6': {'name': 'Enilçek_Ak-Suu',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '7f6751e76767bfe9': {'name': 'Poland_Winter',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'df22809069ffdbd0': {'name': 'Ardennes_Winter',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '0f471b1f1f1f3f02': {'name': 'Maginot_Line_Winter',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '3f1ffcc1811f23f3': {'name': 'Syevyersk-13_Winter',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'ffffff7f3f1f0000': {'name': 'Iberian_Castle',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'fee8c39b9b828000': {'name': 'Test_Site-2271',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'fcfe5e1e1c0802c3': {'name': 'Vlaanderen,_België',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '000c7c7ffffc2400': {'name': 'Aticca',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '000000f0f0f8ffff': {'name': 'Mozdok', #Air Maps
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '003078783c1c8c08': {'name': 'Honolulu',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '8000e0e0c10f0f0f': {'name': 'Strait_of_Dover',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '0781814169e7f0fb': {'name': 'Khalkhyn_Gol',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '080502071f1f0f8f': {'name': 'Ruhrgebiet',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '0f0f0f6737030301': {'name': 'Port_Moresby',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'f7fef9f8d8c08000': {'name': 'Wake_Atoll',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'fcf8f0e0fcfefcfe': {'name': 'Sicily,_Italy',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'e3c188a327f3d9bf': {'name': 'Korsun',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '191fdceddd130382': {'name': 'Palau_Archipelago',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'd90a0000e0f8f0f0': {'name': 'Zhengzhou',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '0f6ffcf8fe781000': {'name': 'Ardennes',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '000018dc3c3fff7b': {'name': 'Afghanistan',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'c3c3c3c3ffffffff': {'name': 'Lake_Lagoda',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '1f1f1c09113fe303': {'name': 'Smolensk',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '7c7eff1f1e1c0800': {'name': 'Cochin_China',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'b8f8f0f0f030f8f8': {'name': 'Tunisia',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '0707d37f17bdecdd': {'name': 'Kursk',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '33363f3f3f333923': {'name': 'Norway',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '0781814169e7f0fb': {'name': 'Khalkhyn_Gol',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'e3c188a327f3d9bf': {'name': 'Korsun',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'f8f87f7f3f070300': {'name': 'Kubanskaya',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '182070381e1e0000': {'name': 'Malta',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '183c3f3e3e1c0800': {'name': 'Midway_Atoll',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'e8e020d0f880e07e': {'name': 'Moscow',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '00c00cb88cbcfcff': {'name': 'Korea',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '080c0700c0f0ff7f': {'name': 'Solomon_Islands',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '07c7041818e0e370': {'name': 'Iwo_Jima',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '5f0f071008808cff': {'name': 'Berlin',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'fffff3bf0f07008c': {'name': 'Mozdok_Winter',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'f8f8f8f0e0e0e0e0': {'name': 'Stalingrad',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '191fdcd9d5130382': {'name': 'Saipan_Island',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'e7ef9fb6f0f0f0e0': {'name': 'Golfo_de_San_Jorge',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '14f4fcfcf8000001': {'name': 'Britain',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '7878fef6ffef80f0': {'name': 'Alameen_Desert',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '0787c7e3c3c0cbcf': {'name': 'Battle_for_the_Rhine',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '0000407c7eff7f7f': {'name': 'Poland',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '000003e6618fdfcf': {'name': 'Normandy',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '0000c0c0b3fbff3e': {'name': 'Vossenack',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '3f0f0384d071383f': {'name': 'France',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '079b8683c5c5c2c2': {'name': 'City',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '00031371fbf0e8f0': {'name': 'Rice_Terraces',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '00183c3c3c180000': {'name': 'Bourbon_Island',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'e08080050fcfefe7': {'name': 'Denmark',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '07070f0f1f1f1f2f': {'name': 'Golan_Heights',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '7c7eff1f1e1c0800': {'name': 'Vietnam',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '6020767717971b83': {'name': 'Sinai',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '7f02f0fe0f008017': {'name': 'Pyrenees',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'decfc3c3a1f0fc7c': {'name': 'Grand_Canyon',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'fcdec8e8b0000000': {'name': 'Rocky_Pillars',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'e1432f3c78200f7f': {'name': 'Southeastern_City',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'c7cf133330307840': {'name': 'Kamchatka',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '00e1ffffc7277fef': {'name': 'Misteryous_Valley',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '0000163f7f7c0000': {'name': 'Falkland_Islands',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '21070701011f1f5e': {'name': 'Himachal_Pradesh',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '080c1c7c70707000': {'name': 'Guam_Island',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '003078783c1c8c08': {'name': 'Oahu',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '1f0f1f7bf3f3bbf9': {'name': 'Findland',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'fcfcd8e46c0e0080': {'name': 'Canyon,_Africa',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'fffc00c0d04080e0': {'name': 'River_Funshion',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'ffc300000000e3ff': {'name': 'Mountain_Ridge',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '3f9f470303e3c7c4': {'name': 'Alpine_Meadows',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
}
