'''
Module to store map metadata for lookup in the mapinfo module

example maps entry: {'0707937f153ccc5d': {'name': 'Kursk',
                             'ULHC_lat': 51.16278580067218,
                             'ULHC_lon': 36.906235369488115,
                             'size_km' : 65},
                     ...}
'''


maps = {'0707937f153ccc5d': {'name': 'Kursk',
                             'ULHC_lat': 51.16278580067218,
                             'ULHC_lon': 36.906235369488115,
                             'size_km' : 65},
        'f0f0e0e0e0f8f8fe': {'name': 'Zaandam,_Nederlands',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '7f7b13f300030001': {'name': 'Eastern_Europe',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '09b36100e6f6fef0': {'name': 'Battle_of_Berlin',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'c0407c5e1b707e3c': {'name': 'Jungle',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '000000c0f0ffffff': {'name': 'El_Alamein',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '002820e062dfdbff': {'name': 'Frozen_Pass',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'fffe0808081f1f3f': {'name': 'Finland',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '181a73fce5e1c183': {'name': 'Battle_of_Hürtgen_Forest',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '80808280c3dfbfff': {'name': 'Ash_River',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '3b80beb0b8fc88e0': {'name': 'Karelia',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '003cf9f3f0e8da2c': {'name': 'Carpathians',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '00c0f0f8d8fcf8f0': {'name': 'Fire_Arc',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'fffeed612361e160': {'name': 'Kuban',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '790d0c3133030301': {'name': 'Mozdok',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'e030650153537066': {'name': 'Normandy',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'f86070a2030b3f0d': {'name': 'Poland',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'c380a0c8c8c0e8e6': {'name': 'Advance_to_the_Rhine',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '7f807efcfafcf0f1': {'name': 'Stalingrad',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'fefcfe1020fefefe': {'name': 'Tunisia',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'f7ef4d1fc0ddfe27': {'name': 'Volokalamsk',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'faf8e8e2f0f8fcfe': {'name': 'Sinai',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '3f0703008081e3df': {'name': '38th_Parallel',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '7f5f370700070f1f': {'name': 'Abandoned_Factory',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'dfe0809061ffdfd0': {'name': 'Ardennes',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'e0e0c0c0c08fffff': {'name': 'Japan',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '083e1e7c7870f0e0': {'name': 'Fulda',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'fcfefdff7e380001': {'name': 'Syria',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'ff0f0f0f07040800': {'name': 'Maginot_Line',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '00003e7e7e7e3c00': {'name': 'Campania',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'fcfcb89808befc0c': {'name': 'American_Desert',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '013e3c7cfefc7c08': {'name': 'Vietnam',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '8e3efe78f87c1e0c': {'name': 'Alaska',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '00307c7c3c3c3c00': {'name': 'Cargo_Port',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '003c7e7e7e7c3c00': {'name': 'Sweden',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '9f1b3efebe740480': {'name': 'Syevyersk-13',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'ffc1d1e0e0f181db': {'name': 'Ennedi_Plateau',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '98807e3e3e0e0c8c': {'name': 'Breslau',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'f9c4fcf1e1c3e3e0': {'name': 'Launch_Facility_Mexico',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'fbffffe6c2c2c880': {'name': 'Aral_teńizi',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'f0f0f8e0c0e0f8f0': {'name': 'Avnat_Isreal',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '8a3efe7cf87c1e0c': {'name': 'Ground_Zero',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'c0e0fcfece60c000': {'name': 'Tkvarcheli_District',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'f3f7a082d3e3e3f8': {'name': 'Himalach_Pradesh',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '04fcfcffdf1c3aed': {'name': 'Nagurskoye_Arkhangyelskaya',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '0f47d38011b89ffc': {'name': 'Enilçek_Ak-Suu',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '7f6751e7636627e9': {'name': 'Poland_Winter',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'dfa2809069ffdfd0': {'name': 'Ardennes_Winter',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '0f471b1f5f1f3f02': {'name': 'Maginot_Line_Winter',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '3f1ffcc1811b23f3': {'name': 'Syevyersk-13_Winter',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'ffffff7f3f1f0000': {'name': 'Iberian_Castle',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'fefcc39bdbc28000': {'name': 'Test_Site-2271',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'e4de5e1e1c080083': {'name': 'Vlaanderen,_België',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '00047cfefffc2400': {'name': 'Aticca',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'fff3f8e0e0c0f0f0': {'name': 'Port_Novorossiysk',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '00000070f0f8ffff': {'name': 'Alaniya,_SSSR',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '0030787c3c1c0c0c': {'name': 'Honolulu',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '8000e0e0810f0f0f': {'name': 'Straight_of_Dover',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '0781014161e7f0fb': {'name': 'Khalkhyn_Gol,_Mongolia',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '080503071f1f0f8f': {'name': 'Ruhrgebiet,_Großdeutsches_Reich',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '0f0f0f2727030301': {'name': 'Port_Moresby',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'fffef9f8d8c08000': {'name': 'Wake_Atoll,_USA',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'fcf8f0f8f4fcfcfe': {'name': 'East_of_Sicily,_Itala',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'e7e1a823a773b9bf': {'name': 'Korsun',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '191f5cfddd1b0382': {'name': 'Palau_Archipelago',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'd9080000e0f8f0f0': {'name': 'Zhengzhou,_China',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '0f6ffcf8fe781000': {'name': 'Ardennes',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '000018dc3c3fff7b': {'name': 'Afghanistan',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'c3c3c3c3ffffffff': {'name': 'Lyeningradskaya_Oblast',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '1f1f1c09113fe343': {'name': 'Smolensk',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '7c7eff3f1e1c0801': {'name': 'CochinChina',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'b8f8f0f0f030f8f8': {'name': 'Tunisia',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '3b373f3f3f333923': {'name': 'Norway',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '082070381e1e0000': {'name': 'Malta',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'e8e0a0f0f880e07f': {'name': 'Moscow',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '00c00cb88cbcfcbf': {'name': 'Korea',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '000c0700c0f0ff7f': {'name': 'Solomon_Islands',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '07c7041810e0e370': {'name': 'Iwo_Jima',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '5f1f071110809cff': {'name': 'Berlin',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'fffff39e0f0700cc': {'name': 'Mozdok_Winter',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'f8f8f8f0e0e0e0e0': {'name': 'Stalingrad',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '191f4cd9d53b0382': {'name': 'Saipan_Island',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        'f7efbfb6f0e0e0e0': {'name': 'Golfo_de_San_Jorge',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '7078faf2ffff80f8': {'name': 'Alameen_Desert',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '44f0fcfcf8000001': {'name': 'Britain',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '0787c7e3c3c1cbcf': {'name': 'Battle_for_the_Rhine',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '000040fc7eff7f7f': {'name': 'Poland',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '000003e6c1cfdfcf': {'name': 'Normandy',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '0000c0c032fbff3e': {'name': 'Vossenack',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '3f0f0384d075303f': {'name': 'France',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
        '03938282c5c5c3c2': {'name': 'City',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0,
                             'size_km' : 65},
}
